// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfm-7ZT00cLaOBPi-wbU0vzkDSkrEk7RM',
    appId: '1:221395183107:web:f9f90efa59388428281036',
    messagingSenderId: '221395183107',
    projectId: 'twitter-ed6bf',
    authDomain: 'twitter-ed6bf.firebaseapp.com',
    storageBucket: 'twitter-ed6bf.appspot.com',
    measurementId: 'G-XY5MQGTL4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe8V5NwgCTIEqyD7wPd6leMhcphJUKNw8',
    appId: '1:221395183107:android:04977f79fa146610281036',
    messagingSenderId: '221395183107',
    projectId: 'twitter-ed6bf',
    storageBucket: 'twitter-ed6bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUu89va8cdyVHNEN8e9bzwslDgCrxnx_M',
    appId: '1:221395183107:ios:b78e57d4c35aaa3a281036',
    messagingSenderId: '221395183107',
    projectId: 'twitter-ed6bf',
    storageBucket: 'twitter-ed6bf.appspot.com',
    iosClientId: '221395183107-7tjsa0c0m1tmuab6ptnfa7g11ihkhb2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUu89va8cdyVHNEN8e9bzwslDgCrxnx_M',
    appId: '1:221395183107:ios:b78e57d4c35aaa3a281036',
    messagingSenderId: '221395183107',
    projectId: 'twitter-ed6bf',
    storageBucket: 'twitter-ed6bf.appspot.com',
    iosClientId: '221395183107-7tjsa0c0m1tmuab6ptnfa7g11ihkhb2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfm-7ZT00cLaOBPi-wbU0vzkDSkrEk7RM',
    appId: '1:221395183107:web:30678598fd7d6f13281036',
    messagingSenderId: '221395183107',
    projectId: 'twitter-ed6bf',
    authDomain: 'twitter-ed6bf.firebaseapp.com',
    storageBucket: 'twitter-ed6bf.appspot.com',
    measurementId: 'G-VERDY9YWN7',
  );

}